### ISSUE TITLE
Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference 

### ISSUE THREAD

**Issue by Broozsoft** [GowenGit/docnet#12]
Hi is there any solution that solve this.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\mkhas\.nuget\packages\docnet.core\1.4.0\lib\netstandard2.0\Docnet.Core.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	SWCG_BRM	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2106

**Comment by Modest-as** [comment]
Hey yes, library only supports 64bit processors so change your build configuration to build for x64 platform target like so `<PlatformTarget>x64</PlatformTarget>`
