### ISSUE TITLE
Constant scaling factor for PageReader

### ISSUE THREAD

**Issue by LokiMidgard** [GowenGit/docnet#13]
The dimensions I pass to `GetDocReader(...)` will be used to scale the PDF to that size. If I have different document with different sizes, those get scaled differently. So the resulting images will have the same size (assuming aspect ration was the same, e.g. A4 and A5 sizes).

Currently one way to workaround it would be using reflection to access private `_scaling` and calculate the original size of the document. Then opening it again with a different px size that was changed so I have a fix resolution.

`GetDocReader()` could have an overload that would take one double that is the resolution PixPer int or PixPerCM.

If interested I could look into it and creating a pull request.

**Comment by Modest-as** [comment]
Hey, you can also try reading and generating images one page at a time if you need more fine control how to scale the pages

**Comment by LokiMidgard** [comment]
That's what I'm currently doing. The problem is I can only specify the absolute result size for every page. Without knowing the original page size I don't know what the result size should be.

My workaround, using reflection to get the scaling and calculate the original size, then create a seccond page:

```c#

public static IPageReader GetPageReader(this DocLib library, string tmp, int pageIndex, double resolution)
{
    int widht, height;

    using (var docReader = library.GetDocReader(tmp, 1024, 1024))
    using (var page = docReader.GetPageReader(pageIndex))
    {
        var type = page.GetType();
        var member = type.GetField("_scaling", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        var scaling = (double)member.GetValue(page);

        var originalHeight = page.GetPageHeight() / scaling;
        var originalWidth = page.GetPageWidth() / scaling;

        widht = (int)(originalWidth * resolution);
        height = (int)(originalHeight * resolution);
    }
    var doc2 = library.GetDocReader(tmp, widht, height);
    var pageReader = doc2.GetPageReader(pageIndex);
    return new PageReader(pageReader, doc2);
}

private class PageReader : IPageReader
{
    private readonly IPageReader pageReader;
    private readonly IDocReader doc2;

    public PageReader(IPageReader pageReader, IDocReader doc2)
    {
        this.pageReader = pageReader;
        this.doc2 = doc2;
    }

    public int PageIndex => this.pageReader.PageIndex;

    public void Dispose()
    {
        this.pageReader.Dispose();
        this.doc2.Dispose();
    }

    public IEnumerable<Character> GetCharacters() => this.pageReader.GetCharacters();

    public byte[] GetImage() => this.pageReader.GetImage();

    public int GetPageHeight() => this.pageReader.GetPageHeight();

    public int GetPageWidth() => this.pageReader.GetPageWidth();

    public string GetText() => this.pageReader.GetText();
}
```

**Comment by Modest-as** [comment]
This is now supported in DocNet 2.0.0
