### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by devel112** [GowenGit/docnet#20]
Anybody else getting these exceptions intermittently?

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.' on GetPageReader(0)

Edit: Fixed when using locks on all usages. Then the question is: is it possible to make it's usage multithreaded?

**Comment by Modest-as** [comment]
Hey, have a look at this and see if it helps https://github.com/GowenGit/docnet/issues/10#issuecomment-586008915

**Comment by devel112** [comment]
#21

**Comment by Modest-as** [comment]
good Idea, merged it in 👍
