### ISSUE TITLE
Support angle for characters

### ISSUE THREAD

**Issue by Bjarnisan** [GowenGit/docnet#22]
It would be nice to be able to supply angle information for the characters found. This will also help in the future for grouping characters into words.

**Comment by Bjarnisan** [comment]
Created a pull request for this issue here
https://github.com/GowenGit/docnet/pull/23

**Comment by Modest-as** [comment]
Hey, thanks for an excellent PR! Would it be possible to add a few tests for it? After that I see no reason not to merge it in.

**Comment by Modest-as** [comment]
Thanks for your PR's again, I was working on some updates so included the code together with some character integration tests in the new release `2.1.3`
