### ISSUE TITLE
Is there an example of how to extract images?

### ISSUE THREAD

**Issue by jboarman** [GowenGit/docnet#32]
I'm looking for a comparative example of how to extract images from a PDF using DocNET.

Here are a couple examples from other libraries I'm looking at:
* UglyPig's Image Extraction Example: https://github.com/UglyToad/PdfPig/blob/master/examples/ExtractImages.cs
* See Patagames "Extracting Images" code example: https://pdfium.patagames.com/

Can this be done in DocNET as well?

**Comment by Modest-as** [comment]
Hey DocNET does not expose access to internal PDF objects, however you can render PDF pages as images if you wish https://github.com/GowenGit/docnet/blob/master/examples/nuget-usage/NugetUsageAnyCpu/PdfToImageExamples.cs
