### ISSUE TITLE
How to use the Split-Method?

### ISSUE THREAD

**Issue by rubiktubik** [GowenGit/docnet#36]
I want to split a large pdf document in smaller documents.

```cs
var bytes = DocLib.Instance.Split("MyPDF.pdf","1,1,1");
```

But how do i get the 3 separate pages from these bytes?

**Comment by Modest-as** [comment]
Split method returns current split, so if you want to split only first 3 pages into a separate PDF file you would do `var bytes = DocLib.Instance.Split("MyPDF.pdf","0,1,2");`

**Comment by Modest-as** [comment]
It does not generate multiple files, only a file of your specified page range
