### ISSUE TITLE
strong name signed version on nuget

### ISSUE THREAD

**Issue by boltomli** [GowenGit/docnet#37]
**Is your feature request related to a problem? Please describe.**
Hit the problem `A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)` on Windows when the app requires.

**Describe the solution you'd like**
Perhaps sign the lib? I'm not sure how to make it yet, however.

**Describe alternatives you've considered**
The app based on the lib would turn the feature off, but that would reduce the overall security sometimes.

**Additional context**

**Comment by boltomli** [comment]
This might be the steps to do so <https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name>

**Comment by Modest-as** [comment]
Hey, this library purely targets .net core and .net 5 for which strong-named assemblies do not provide material benefits. https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named  . Out of curiosity what target framework are you running against?

**Comment by boltomli** [comment]
Yes, it's not useful for core, but for framework I need the following from the doc `You want to enable your assemblies to be referenced by strong-named assemblies`
