### ISSUE TITLE
Is there a way to create a PDF and add pages?

### ISSUE THREAD

**Issue by chrisnurse** [GowenGit/docnet#38]
I need to be able to create a new page and content and insert it into a target PDF.

Currently I'm merging multiple inputs into a single output PDF.
I want to insert an index page, showing the list of documents, and which page number they appear at in the output. 
So, the output document would be an index page, followed by all of the inputs concatenated together.

I don't seem to be able to find a way to create PDFs or pages in DocNet. Seems pretty fundamental to a PDF toolkit.

**Comment by Modest-as** [comment]
There are excellent open source libraries out there that do PDF creation e.g. https://github.com/UglyToad/PdfPig. DocNET does not try to replicate that, it does everything else.

**Comment by chrisnurse** [comment]
I'll mark this as closed then. One less user of DocNet.
