### ISSUE TITLE
PDF to image not working in Azure

### ISSUE THREAD

**Issue by kinhoon** [GowenGit/docnet#4]
The sample code at `https://github.com/GowenGit/docnet/blob/master/examples/pdf-to-image/PdfToImage/Program.cs` uses `System.Drawing.Common`, but it is not supported in Azure.

Can you provide a sample using SkiaSharp?

Thanks

**Comment by Modest-as** [comment]
Hi,

Yes, you are correct, the example there uses `System.Drawing.Common` and you would need to install dependencies on your azure environment if you want to use it. I am currently on holiday so will not get around to implementing anything in SkiaSharp for a few weeks at least. If you are in a hurry, the image format that `docnet` returns is a BGRA raw byte array, I have found this helpful github [issue](https://github.com/mono/SkiaSharp/issues/416) that will help you if you want to try and do it yourself.

**Comment by kinhoon** [comment]
Hi,

I tested further and found that `GetText()` function is also not working in Azure Web App.

I checked further and realized that the pdfium.dll dependency for Docnet.dll actually linked to gdi32.dll. I read from the following link that Azure sandbox actually block any dependency to GDI calls
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

If this is the case, it could simply mean we will not be able to use Docnet in Azure Web App. Though it works perfectly fine in IIS deployment locally.

**Comment by Modest-as** [comment]
Yes, that is correct, `PDFium` uses `GDI` in a couple of [places](https://github.com/PDFium/PDFium/search?q=gdi&unscoped_q=gdi) when running on Windows. This, however, is not an issue on Linux since pdfium.so doesn't need `GDI`. If you can't run on Linux or use `GDI`, unfortunately, there are only two alternatives:

1) Try to compile `PDFium` without GDI dependencies
2) Try to find some other library that doesn't use `GDI`

Hope this helps.

Thanks,

Modestas

**Comment by kinhoon** [comment]
It seems it is quite impossible to remove GDI dependencies from `PDFium`. Seems the only way is to find another library. :-(

Thanks.

**Comment by Modest-as** [comment]
I will be closing this feature request since we can't realistically expect to remove GDI dependencies from windows build of `PDFium`. Suggested workaround if running on Azure and the project supports `netstandard` is to try and run on Linux.
