### ISSUE TITLE
.GetText() works, .GetImage() doesn't on first page on test file, wikipedia_0.pdf

### ISSUE THREAD

**Issue by Triazic** [GowenGit/docnet#40]
**Describe the bug**
.GetText() works, .GetImage() doesn't on first page of your test file, wikipedia_0.pdf

**To Reproduce**
1. use .net 5.0
2. add Docnet.Core package and System.Drawing.Common
3. build unit test involving .GetText and .GetImage
4. Fails

**Expected behavior**
Image is created

**Screenshots**
![image](https://user-images.githubusercontent.com/38064196/118904489-58551480-b95d-11eb-99c6-c0ebecd7c776.png)

**Desktop (please complete the following information):**
Windows
.net 5
unit test via Microsoft.VisualStudio.TestTools.UnitTesting

**Comment by Triazic** [comment]
also I can't see pdfium.dll anywhere in my repo. Should I have downloaded this externally and set up the copying manually in csproj etc?

**Comment by Modest-as** [comment]
Hi, I couldn't replicate this, you don't need to do anything. Just clone the latest master, then restore nuget packages and run tests in `NugetUsageAnyCpu` csproj.

**Comment by Triazic** [comment]
This wasn't using the source, this was using the published version of Docnet.Core on NuGet. https://www.nuget.org/packages/Docnet.Core/2.2.0
I got your test pdf from source, though

Would have been 2.2.0 at the time
