### ISSUE TITLE
Include pdfium without extension for Mac OS X runtime

### ISSUE THREAD

**Issue by andrei-gubarev** [GowenGit/docnet#44]
Hello,
I tried to run my solution that is targeted to .Net Framework 4.7 with Mono on mac os x and it returned me the error "pdfium not loaded". Actually, I spent a few hours trying to understand what's the issue until got help from my teammates. My output folder included the file pdfium.dylib but still didn't work. The workaround was to remove extension ".dylib" from the file on the output folder.
The file pdfium.dylib is loaded successfully by .net core apps but not from Mono. Of course, using Mono with the library is a rare case, but one improvement can be to check if the environment is Mono then copy the file without extension or copy both files if runtime is mac os x.

Just wanted to report in case if it can save time to other developers.

**Comment by Modest-as** [comment]
Thanks, .NET Framework and mono support was added only as experimental feature, I do not think that we will aim to fully support it due to EOL.
