### ISSUE TITLE
Efficient memory usage in the case of big PDF Merge operations

### ISSUE THREAD

**Issue by undrivendev** [GowenGit/docnet#45]
**Is your feature request related to a problem? Please describe.**
We have a requirement which involves merging quite a lot of PDF files, and the library seems not to scale well with the increasing size (or number) of the PDF files involved. 
To be specicific, we perform a number of sequential calls to a web API and we get a PDF file that we store in memory as a `byte[]`. Every time, we call the `Merge(byte[], byte[])` method and we build (in memory) the PDF corresponding to the 'sum' of all the previous ones. Then we save it.
The problem is that the operation is quite heavy memory-wise because the result gets bigger and bigger and we end up often with a `OutOfMemoryException`.

**Describe the solution you'd like**
Some kind of PDF merge operation that allows us to avoid loading the result into memory (maybe using, for example, some kind of output `Stream`).

**Describe alternatives you've considered**
We've considered splitting up the operation and save multiple smaller files instead of a big one, but that's not something we can do for backwards compatibility reasons.

**Additional context**
Here's an example Console App I've done for testing purposes demonstrating the issue:
```
static async Task Main(string[] args)
{
    byte[]? accumulator = null;
    var files = Directory.EnumerateFiles(@"C:\temp\pdfs").ToList();
    for (int i = 0; i < files.Count(); i++)
    {
        if (i == 0)
        {
            accumulator = await File.ReadAllBytesAsync(files[i]);
            continue;
        }

        accumulator = DocLib.Instance.Merge(accumulator, await File.ReadAllBytesAsync(files[i]));
    }

    await using var sResult = File.OpenWrite(@"C:\temp\pdfs\all.pdf");
    await sResult.WriteAsync(accumulator);
} 
```
Thank you for the project.

**Comment by Modest-as** [comment]
hey, `Merge` method also takes file paths, did you try using that instead?

**Comment by Modest-as** [comment]
dealing with streams in this case is not trivial since we are limited to what pdfium exposes and as far as I know there is no interface exposed to marshal byte streams
