### ISSUE TITLE
Bug on specific control in BoundBox class: "Validator.CheckOrder"

### ISSUE THREAD

**Issue by yvainb** [GowenGit/docnet#49]
I encountered an issue with the pageReader.GetCharacters() method. With pdf file if the text is written from bottom to top, the control Validator.CheckOrder returns an exception.

To solve this problem, i had to delete these controls "Validator.CheckOrder":
![ForkDocNet](https://user-images.githubusercontent.com/22787451/133246968-c2f03dd4-8eb7-4f30-8c1b-de6bdb06bd5f.png)

After many tests on many pages (+100000) on many documents (+30000). Validator.CheckOrder is useless.
It would be preferable to delete it.

**Comment by Modest-as** [comment]
Pull requests are very much welcome, I don't see why we couldn't remove the check, we just need some test docs that break and more test cases added.

**Comment by Bjarnisan** [comment]
I get this issue a lot with pdfs generated from CAD files. Sometimes the bounding boxes are flipped so left and right (or top and bottom) switch places. I can't share any of these documents, but I'll see if I'm able to create a cropped version or something.

**Comment by Modest-as** [comment]
Check will be removed in the next release
