### ISSUE TITLE
Save page image

### ISSUE THREAD

**Issue by ferronsw** [GowenGit/docnet#5]

**Comment by Modest-as** [comment]
Hey, I imagine you have imported `System.Drawing. Common`?

**Comment by ferronsw** [comment]
I did, but I forgot to copy your two static methods…
Sorry, but thanks for the response!

Van: Modestas <notifications@github.com>
Verzonden: dinsdag 14 mei 2019 15:37
Aan: GowenGit/docnet <docnet@noreply.github.com>
CC: Ferron Nijland - Switch IT Solutions <f.nijland@switch.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [GowenGit/docnet] Save page image (#5)


Hey, I imagine you have imported System.Drawing. Common?
