### ISSUE TITLE
Incorrect scalingFactor documentation

### ISSUE THREAD

**Issue by jahav** [GowenGit/docnet#54]
# Incorrect scalingFactor documentation 
The documentation for PageDimensions ctor describes the `scalingFactor` as
> Page scaling PPI factor

However, it seems to be incorrect, based on my experimentations, it is pixels per point factor, where 72 points is equal to one inch.
Example: I want 300 pixels per inch = scaling factor should be 300/72 ~ 4.1666666

Could it be changed to something like?
> Page scaling factor in pixels-per-point. Convert PPI to scaling factor as PPI/72.

**Comment by Modest-as** [comment]
good suggestion, updated on master

**Comment by LonelyReligion** [comment]
Weird question, but I have trouble finding project's documentation. It's trivial, but I've been searching for over an hour now.
