### ISSUE TITLE
Converting PDF to image containing form fields returns blank fields

### ISSUE THREAD

**Issue by vinishiru** [GowenGit/docnet#57]
When calling the "GetImage" function with a PDF file that contains "Form Fields", the generated image does not contain the form fields values, becoming all blank after the operation.

We tried to change the RenderFlags used as arguments to GetImage function, but with no success at all.

Here is the code snippet that I used:

```C#
using (var docReader = rasterizer.GetDocReader(pdfBuffer, new Docnet.Core.Models.PageDimensions(1080, 1920)))
        for (var i = 0; i < docReader.GetPageCount(); i++)
        {
          using (var pageReader = docReader.GetPageReader(i))
          {
            var pageBytes = pageReader.GetImage(new NaiveTransparencyRemover(255, 255, 255), RenderFlags.RenderForPrinting);

            return BytesToBitmap(pageReader, pageBytes, dpi);
          }
        }
```

Is there anything, or any argument missing when calling the GetImage function to get the desired result?

Here follows the screenshots before and after the operations.

Screenshot before converting.
![image](https://user-images.githubusercontent.com/924290/147291437-278c35dc-29eb-405d-a35b-4c3c9909d93c.png)

Screenshot after converting.
![image](https://user-images.githubusercontent.com/924290/147291393-53b87dd9-2892-4070-9c37-75a5772a70b5.png)

Original PDF.
[OriginalFilledForms.pdf](https://github.com/GowenGit/docnet/files/7771375/OriginalFilledForms.pdf)

Thanks in advance.

**Comment by vinishiru** [comment]
Hi there.
I now realized, after studying how Pdfium render annotations and FormFills, how to make it work.
Is there any contribute guide lines before I can send an PR?
Thanks.

**Comment by Modest-as** [comment]
Hey, no strict guidelines, link the Issue in the PR, make sure that code follows the existing styles and add a few tests
