### ISSUE TITLE
Support rendering of a page to a graphics object (DeviceContext)

### ISSUE THREAD

**Issue by gebolze** [GowenGit/docnet#66]
I have been trying to use the docnet library to print pdf files. To do this, I currently need to get an image of the pdf page as a byte array and then load that into a bitmap and finally render it using the Graphics object when printing. Technically this works fine, but is relatively slow since rendering of the image is done using the Graphics [DrawImage](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.drawimage?view=dotnet-plat-ext-6.0) method.

It should be possible to improve performance if, instead of marshaling the image data twice, I could render the image directly into the underlying DeviceContext of the Graphics object. The [FPDF_RenderPage](https://pdfium.googlesource.com/pdfium/+/refs/heads/main/public/fpdfview.h#791) function could be used for this. This function is only available on Windows so an exception would be required if it is run on another operating system.

If this feature is accepted, I am able to provide an initial implementation.

**Comment by Modest-as** [comment]
Hey, I have tried to make this library as cross platform as possible so all the functionality works regardless of the platform, but as long as there are no 3rd party dependencies except pdfium I think it would be an acceptable addition, since pdfium itself exposes that method, we can play around with setting `SupportedOSPlatform` attribute too.

**Comment by gebolze** [comment]
Is there any chance the PR gets merged? It's now open for more than a month. If there is something missing or something I can support with just ping me and I'll try to support if possible. Thanks!

**Comment by gebolze** [comment]
No updates over the last 6 month. For us it's clear that we can't use this library for our needs and we will now look for alternatives.

**Comment by Modest-as** [comment]
Pushed as part of `2.5.0-alpha.1`
