### ISSUE TITLE
left coordinate can't be more than right coordinate

### ISSUE THREAD

**Issue by mirkofisic** [GowenGit/docnet#71]
We have a problem with certain PDF files, in some documents we get this error:

> left coordinate can't be more than right coordinate, STACK:   at Docnet.Core.Validation.Validator.CheckOrder(Int32 coordOne, Int32 coordTwo, String nameOne, String nameTwo)
   at Docnet.Core.Models.BoundBox..ctor(Int32 left, Int32 top, Int32 right, Int32 bottom)
   at Docnet.Core.Readers.PageReader.<GetCharacters>d__10.MoveNext()

**Is it possible to add a specific property that will avoid this validation on BoundBox class so that the developer can later do his own validation?**

We don't know exactly where the problem is and on what character this is happening, but this only happens on certain documents, we also have an example that we can send you if you could look at it and determine the real reason?

I must also emphasize that if I insert the same PDF into some other software such as ABBYY it does not report any error and all the characters are read properly.

**Comment by Modest-as** [comment]
Hey, that check was removed in the latest alpha release, please use that instead.

**Comment by mirkofisic** [comment]
Can i download alpha version through package manager or I need to build? Are there any major changes in the alpha version I ask this due to changes in code and functionality?
