### ISSUE TITLE
Page Dimensions

### ISSUE THREAD

**Issue by gmlloves** [GowenGit/docnet#72]
Hello,  I want to print a ticket with paper size: 70mm x 40mm.
I get an error at line: using var _reader = DocLib.Instance.GetDocReader(pdf, pageDim);

 'dimOne can't be more than dimTwo'
   en Docnet.Core.Validation.Validator.CheckNotGreaterThan(Int32 valueOne, Int32 valueTwo, String nameOne, String nameTwo)
   en Docnet.Core.Models.PageDimensions..ctor(Int32 dimOne, Int32 dimTwo)

Can you allow the width is greater then the height, please?

**Comment by gmlloves** [comment]
Hi, thank you for your response.
  
I got the 2.4.0-alpha.3 version and I get the same error. PageDimensions constructor checks it:

 public PageDimensions(int dimOne, int dimTwo)
        {
        ....
            Validator.CheckNotGreaterThan(dimOne, dimTwo, nameof(dimOne), nameof(dimTwo));

**Comment by Modest-as** [comment]
ah sorry this is for dimensions, make sure that first dimension you specify is less than the second dimension, they do not indicate width vs height, just max viewport aspect ratios

**Comment by gmlloves** [comment]
Thank you very much!
