### ISSUE TITLE
pdfium.dll locked by IIS/IIS Express

### ISSUE THREAD

**Issue by Mindless73** [GowenGit/docnet#75]
We are using V2.4.0 alpha4 (from Nuget) in a Web Forms project (.net 4.8).

The initial run works fine, DLL is copied and loaded fine. Works perfectly
The next time a build is attempted (in Visual Studio ) I get the following error:

`Unable to copy file ...\packages\Docnet.Core.2.4.0-alpha.4\runtimes\win-x64\native\pdfium.dll" to "bin\pdfium.dll".
The process cannot access the file 'bin\pdfium.dll' because it is being used by another process.`

Killing the "IIS Worker Process" resolves the issue, but isn't a practical solution.

The same happens when using it on IIS. Again, the initial run works fine and DLL is copied and loaded fine.
When trying to publish the site, the `bin` directory can not be deleted, because 'bin\pdfium.dll' is locked by the web server.

Recycling the app pool of the website solves the problem, but again, that isn't really a practical solution.

Is there any way to release the lock after using docnet?

**Comment by Modest-as** [comment]
This happens because your webserver has the file handle locked when you have it running. Does this still happen if you dispose the docnet instance straight after you finish using it or the lifetime of docnet linked to the lifetime of your web server?
