### ISSUE TITLE
Performance comparison to other pdfium based libs

### ISSUE THREAD

**Issue by unwork-ag** [GowenGit/docnet#76]
I have been starting to look for alternatives to iText7 for text extraction since iText has issues with some pdf documents that I need to handle which seem to have an uncommon (but still valid) encoding. docnet can handle these and all other documents that I used for the comparison just fine. In a next step I was looking at the extraction performance and I found that there are significant differences between the various libs that are pdfium based (currently looking at docnet, Patagames Pdfium.NET SDK and ironPDF).

I found that docnet was performing significantly slower than Patagames for a 63 page PDF document of about 1.5 MB (1.3 seconds vs 200 ms - measured with benchmarkdotnet). Would could be a reason that pdfium based text extraction has such significant performance differences? Are there any options to do extraction using docnet differently that I could try out?

Currently my code looks like this:
```
        using (var docReader = DocLib.Instance.GetDocReader(opts.FilePath, new PageDimensions()))
        {
            for (var i = 0; i < docReader.GetPageCount(); i++)
            {
                using (var pageReader = docReader.GetPageReader(i))
                {
                    var text = pageReader.GetText();
                    AddTextToResult(text, opts);
                }
            }
        }
```

**Comment by majora2007** [comment]
I ran into this problem myself with image extraction. What I ended up doing was parallelizing the extraction code to get a major speed up.

Here is a link to the code I wrote:
https://github.com/Kareadita/Kavita/blob/e455da0686c4d2e28cacd304729a1d12c78cabbd/API/Services/BookService.cs#L647

Hope that helps you.

**Comment by unwork-ag** [comment]
@majora2007 : thanks - I will give it a try!

**Comment by Modest-as** [comment]
Have to close this since I am pursuing different wasm based direction for future docnet versions
