### ISSUE TITLE
The type or namespace name 'Docnet' could not be found in net45

### ISSUE THREAD

**Issue by mayurjansari** [GowenGit/docnet#77]
**Describe the bug**
Nuget package show support for net45 but when we install package it can't find refrence for net45 and showing error
"The type or namespace name 'Docnet' could not be found
(are you missing a using directive or an assembly reference?)"

**To Reproduce**
1. create project with net45 target
2. Go to manage nuget package and install docnet
3. add some code to get page image

**Comment by Modest-as** [comment]
Sorry, net framework will not be officially supported anymore, if it works for newer versions of it for now so be it, but net45 is long gone.
