### ISSUE TITLE
Transparency issues when generating jpeg image 

### ISSUE THREAD

**Issue by mKenfenheuer** [GowenGit/docnet#8]
Basically Docnet generates black background instead of white or transparent.

[003_Test_Output (1).zip](https://github.com/GowenGit/docnet/files/3663999/003_Test_Output.1.zip)
[003_Test.pdf](https://github.com/GowenGit/docnet/files/3664000/003_Test.pdf)

**Comment by Modest-as** [comment]
This is not an issue, the library will generate whatever is presented in the PDF file, if file has no background specified it will treat that as transparent, you can always specify background layer to whichever color you want depending on your image processing library, just replace empty  pixels with whatever `Format32bppArgb` value you want

**Comment by mKenfenheuer** [comment]
@Modest-as 

do you have an example on how to do this?

**Comment by Modest-as** [comment]
Sure, something like this:

```

**Comment by mKenfenheuer** [comment]
Thanks for your help, this pointed me into the right direction.

Your code worked well, but not a 100% fit for my case (i had also transparent font smoothing).

I Just had to create a white image and "print" the document onto it.

the code below now works for me:

```
public static byte[] ConvertPdfToJpeg(this byte[] data, int rwidth = 1080, int rheight = 1920)
        {
            using (var library = DocLib.Instance)
            {
                using (var docReader = library.GetDocReader(data, rwidth, rheight))
                {
                    using (var pageReader = docReader.GetPageReader(0))
                    {
                        var rawBytes = pageReader.GetImage();
                        var width = pageReader.GetPageWidth();
                        var height = pageReader.GetPageHeight();
                        using (var doc = new Bitmap(width, height, PixelFormat.Format32bppArgb))
                        using (var bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb))
                        {
                            bmp.AddBytes(rawBytes);
                            for (int y = 0; y < bmp.Height; y++)
                            {
                                bmp.SetPixel(bmp.Width - 1, y, bmp.GetPixel(bmp.Width - 2, y));
                            }
                            Graphics g = Graphics.FromImage(doc);
                            g.FillRegion(Brushes.White, new Region(new Rectangle(0, 0, width, height)));
                            g.DrawImage(bmp, new Point(0, 0));
                            g.Save();
                            using (var stream = new MemoryStream())
                            {
                                doc.Save(stream, ImageFormat.Jpeg);
                                return stream.ToArray();
                            }
                        }
                    }
                }
            }
        }
````

**Comment by jaredbaszler** [comment]
@mKenfenheuer 

> Thanks for your help, this pointed me into the right direction.
> 
> Your code worked well, but not a 100% fit for my case (i had also transparent font smoothing).
> 
> I Just had to create a white image and "print" the document onto it.
> 
> the code below now works for me:
> 
> ```
> public static byte[] ConvertPdfToJpeg(this byte[] data, int rwidth = 1080, int rheight = 1920)
>         {
>             using (var library = DocLib.Instance)
>             {
>                 using (var docReader = library.GetDocReader(data, rwidth, rheight))
>                 {
>                     using (var pageReader = docReader.GetPageReader(0))
>                     {
>                         var rawBytes = pageReader.GetImage();
>                         var width = pageReader.GetPageWidth();
>                         var height = pageReader.GetPageHeight();
>                         using (var doc = new Bitmap(width, height, PixelFormat.Format32bppArgb))
>                         using (var bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb))
>                         {
>                             bmp.AddBytes(rawBytes);
>                             for (int y = 0; y < bmp.Height; y++)
>                             {
>                                 bmp.SetPixel(bmp.Width - 1, y, bmp.GetPixel(bmp.Width - 2, y));
>                             }
>                             Graphics g = Graphics.FromImage(doc);
>                             g.FillRegion(Brushes.White, new Region(new Rectangle(0, 0, width, height)));
>                             g.DrawImage(bmp, new Point(0, 0));
>                             g.Save();
>                             using (var stream = new MemoryStream())
>                             {
>                                 doc.Save(stream, ImageFormat.Jpeg);
>                                 return stream.ToArray();
>                             }
>                         }
>                     }
>                 }
>             }
>         }
> ```

@mKenfenheuer - thanks a bunch.  I had exactly the same problem as you had experienced.  You saved me a BUNCH of time.  Thanks for the code example!!!

**Comment by hmdhasani** [comment]
I think the library should treat like this as default.
