### ISSUE TITLE
Better memory allocations when creating images from the pdf

### ISSUE THREAD

**Issue by Hafman08** [GowenGit/docnet#93]
**Is your feature request related to a problem? Please describe.**
When trying to convert a pdf with many pages to images, IPageReader.GetImage will create a lot of allocations in LOH if the size of the image is greater than 85000 bytes and this puts pressure on the GC that will be triggered multiple times fragmenting LOH more each time.

**Describe the solution you'd like**
I would like GetImage to receive a byte[] and the image from the unmanaged memory to be copied to the provided array.

**Describe alternatives you've considered**
I would like to use ArrayPool<byte> for pooling the arrays required by the images.

**Additional context**
I tried to run some benchmarks and for PageDimensions (1275, 1650) and 50 pages I've got this results:
![image](https://github.com/GowenGit/docnet/assets/9305899/735dc92e-78f6-4eaf-8d42-7b512117dd40)
It almost checks out the memory allocated on the method without the array pool: 1275 * 1650 * 4 * 50 = 412 500 000 .

**Comment by Modest-as** [comment]
Hello, I've tagged this as an enhancement, maybe someone pick this one up or I will do it myself when I have some time

**Comment by Hafman08** [comment]
Can I try to implement it ? Maybe also add an example for it.

**Comment by Modest-as** [comment]
Thanks for the PR, will include this in the next release, probably will rename to `WriteImageToBuffer` though
